services:
  mysql:
    image: mysql:latest
    container_name: batch-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: batch
      MYSQL_USER: batch_user
      MYSQL_PASSWORD: batch_password